name: Hugo realease version bump

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Login to GitHub API
        run: gh auth login --with-token ${{ secrets.TOKEN_GITHUB }}
  
      - name: Check latest release tag
        id: hugo_tag
        run: |
          releases=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/gohugoio/hugo/releases?per_page=1&page=1)
          release_tag=$(echo $releases | jq '.[0].tag_name' | sed 's/v//' | sed 's/"//g')
          echo "hugo_latest_release_tag=${release_tag}" >> $GITHUB_OUTPUT

      - name: Identify latest release branch
        run: |
          git fetch -a origin
          latest_branch=$(git branch -r --sort=committerdate | grep -E "*/release/*" | tail -1)
          echo "latest_branch=${latest_branch}" >> $GITHUB_OUTPUT

      - name: Create new release branch and run version bump
        if: env.release_tag != env.hugo_latest_release_tag 
        run: |
          git checkout release/${{ env.hugo_latest_release_tag }}
          version=${{env.hugo_latest_release_tag}} make bump
          git add -A
          git commit -m "hugo version bump to ${{env.hugo_latest_release_tag}}"
          git push origin release/${{env.hugo_latest_release_tag}}:release/${{env.hugo_latest_release_tag}}

      - name: Create new PR with latest release branch
        run: |
        gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/floryn90/docker-hugo/pulls -f title="Hugo version bump to ${{env.hugo_latest_release_tag}}" -f body='Hugo version bump to ${{env.hugo_latest_release_tag}}' -f head="octocat:release/${{env.hugo_latest_release_tag}}" -f base='master' 
      
      - name: Create new release tag
        run: |
        gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/floryn90/docker-hugo/releases -f tag_name='v${{env.hugo_latest_release_tag}}' -f target_commitish='master' -f name="Hugo version v${{env.hugo_latest_release_tag}}"" -f body="Hugo release version bump to ${{env.hugo_latest_release_tag}}" -F draft=false -F prerelease=false -F generate_release_notes=false 
          